# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_hub_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('visitor', 'Regular Visitor'), ('performer', 'Performing Artist')], default='visitor', max_length=20),
        ),
    ]
