# Generated by Django 6.0.3 on 2026-04-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_type',
        ),
    ]
