# Generated by Django 6.0.3 on 2026-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of units available (Applicable for Gear/Instruments)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired/Broken')], default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Applicable for Halls (Number of people)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('hall', 'Space/Hall'), ('gear', 'Equipment/Gear'), ('instrument', 'Musical Instrument')], max_length=15),
        ),
    ]
