# Generated by Django 6.0.2 on 2026-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_gig_alter_resource_capacity_alter_resource_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(help_text='Name of the artist', max_length=200)),
                ('story', models.TextField(help_text='The success story text')),
                ('image', models.ImageField(help_text='Artist image or story image', upload_to='success_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on landing page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
