# Generated by Django 6.0.3 on 2026-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigapplication',
            name='voice_message',
            field=models.FileField(blank=True, help_text='Voice recording alternative to text message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='gigapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Why should you get this gig?'),
        ),
    ]
