# Generated by Django 6.0.3 on 2026-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_gigapplication_voice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigapplication',
            name='transcribed_text',
            field=models.TextField(blank=True, help_text='Transcribed text from voice message'),
        ),
    ]
