# Generated by Django 6.0.3 on 2026-04-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_gigapplication_transcribed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigapplication',
            name='transcribed_text',
        ),
    ]
