# Generated by Django 6.0.3 on 2026-04-15 13:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_gigapplication_transcribed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='resource',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource_image'),
        ),
        migrations.AlterField(
            model_name='gigapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gigapplication',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='artist_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='success_story_image'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='story',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.booking')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
